#!/usr/bin/env sh

if [ -z "$1" ]; then
    echo "Usage: $0 <filename>"
    exit 1
fi

FILE="$1"
EMAIL="christopher.flinn@gmail.com"

HASH=$(openssl dgst -sha256 "$FILE" | awk '{print $2}')

BASENAME=$(basename "$FILE" .txt)
NEXT_NUM=1

while [ -e "${BASENAME}_${NEXT_NUM}.txt" ]; do
    NEXT_NUM=$((NEXT_NUM + 1))
done

COPY_FILE="${BASENAME}_${NEXT_NUM}.txt"
echo "$HASH" > "$COPY_FILE"

git add .
git commit -m "Added $FILE with hash: $HASH"
git push
